/**
 * SSLCommerz Refund Helper - Chapter 3 Step 3.2
 *
 * Purpose: Simplified interface for refund operations
 * Location: server/ssl/api/refund-helper.ts
 *
 * This is a wrapper around SslCommerzPayment that provides
 * better TypeScript types and easier-to-use methods.
 */

import { SslCommerzPayment } from './payment-controller'

// ========================================================
// TypeScript Interfaces for Refund Operations
// ========================================================

export interface RefundInitiateParams {
  /** Original bank transaction ID from payment */
  bank_tran_id: string
  /** Unique refund transaction ID (generated by your system) */
  refund_trans_id: string
  /** Amount to refund */
  refund_amount: number | string
  /** Reason for refund */
  refund_remarks: string
  /** Optional: Your internal reference ID */
  refe_id?: string
}

export interface RefundInitiateResponse {
  APIConnect: 'DONE' | 'INVALID_REQUEST' | 'FAILED' | 'INACTIVE'
  bank_tran_id: string
  trans_id: string
  refund_ref_id: string
  status: 'success' | 'failed' | 'processing'
  errorReason: string
}

export interface RefundQueryParams {
  /** Refund reference ID from initiate response */
  refund_ref_id: string
}

export interface RefundQueryResponse {
  APIConnect: 'DONE' | 'INVALID_REQUEST' | 'FAILED' | 'INACTIVE'
  bank_tran_id: string
  tran_id: string
  refund_ref_id: string
  initiated_on: string
  refunded_on: string | null
  status: 'refunded' | 'processing' | 'cancelled' | 'failed'
  errorReason: string
}

// ========================================================
// Refund Helper Class
// ========================================================

/**
 * SSLCommerzRefundHelper - Simplified refund operations
 *
 * Usage:
 *   const refundHelper = new SSLCommerzRefundHelper()
 *   const result = await refundHelper.initiateRefund(params)
 */
export class SSLCommerzRefundHelper {
  private payment: SslCommerzPayment

  constructor(live = false) {
    // Get credentials from runtime config
    const config = useRuntimeConfig()
    const storeId = config.public?.supabaseUrl
      ? this.extractStoreId(config.public.supabaseUrl)
      : process.env.SSLCOMMERZ_STORE_ID || 'testbox'
    const storePassword = process.env.SSLCOMMERZ_STORE_PASSWORD || 'qwerty'

    this.payment = new SslCommerzPayment(storeId, storePassword, live)
  }

  /**
   * Extract store ID from Supabase URL (if needed)
   * Format: https://xxxxx.supabase.co -> xxxxx
   */
  private extractStoreId(supabaseUrl: string): string {
    try {
      const url = new URL(supabaseUrl)
      // For SSLCommerz, you might need a different approach
      // This is just a placeholder
      return process.env.SSLCOMMERZ_STORE_ID || 'testbox'
    }
    catch {
      return 'testbox'
    }
  }

  /**
   * Initiate a refund transaction
   *
   * @param params - Refund parameters
   * @returns Promise<RefundInitiateResponse>
   */
  async initiateRefund(params: RefundInitiateParams): Promise<RefundInitiateResponse> {
    try {
      const response: any = await this.payment.initiateRefund({
        bank_tran_id: params.bank_tran_id,
        refund_trans_id: params.refund_trans_id,
        refund_amount: params.refund_amount,
        refund_remarks: params.refund_remarks,
        refe_id: params.refe_id,
      })

      // Parse and validate response
      return {
        APIConnect: response.APIConnect || 'FAILED',
        bank_tran_id: response.bank_tran_id || '',
        trans_id: response.trans_id || '',
        refund_ref_id: response.refund_ref_id || '',
        status: response.status || 'failed',
        errorReason: response.errorReason || '',
      }
    }
    catch (error: any) {
      console.error('[SSLCommerzRefund] initiateRefund error:', error)
      throw new Error(`Refund initiation failed: ${error.message}`)
    }
  }

  /**
   * Query refund status
   *
   * @param params - Query parameters
   * @returns Promise<RefundQueryResponse>
   */
  async queryRefundStatus(params: RefundQueryParams): Promise<RefundQueryResponse> {
    try {
      const response: any = await this.payment.refundQuery({
        refund_ref_id: params.refund_ref_id,
      })

      // Parse and validate response
      return {
        APIConnect: response.APIConnect || 'FAILED',
        bank_tran_id: response.bank_tran_id || '',
        tran_id: response.tran_id || '',
        refund_ref_id: response.refund_ref_id || '',
        initiated_on: response.initiated_on || '',
        refunded_on: response.refunded_on || null,
        status: response.status || 'failed',
        errorReason: response.errorReason || '',
      }
    }
    catch (error: any) {
      console.error('[SSLCommerzRefund] queryRefundStatus error:', error)
      throw new Error(`Refund status query failed: ${error.message}`)
    }
  }

  /**
   * Generate a unique refund transaction ID
   * Format: REF-{timestamp}-{random}
   */
  static generateRefundTransId(prefix = 'REF'): string {
    const timestamp = Date.now().toString(36)
    const random = Math.random().toString(36).substring(2, 8)
    return `${prefix}-${timestamp}-${random}`
  }
}

// ========================================================
// Export default instance for easy use
// ========================================================

export default SSLCommerzRefundHelper
